# Generated by Django 4.1.3 on 2022-11-25 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual', models.BooleanField(default=False)),
                ('imdbID', models.CharField(max_length=10)),
                ('tmdbID', models.IntegerField(blank=True, default=0)),
                ('tmdb_BASE_PATH', models.CharField(blank=True, default='', max_length=20)),
                ('year', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(default='', max_length=200)),
                ('ratingIMDb', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3)),
                ('ratingTMDb', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3)),
                ('ratingRT', models.CharField(blank=True, default='', max_length=10)),
                ('ratingMetascore', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=3)),
                ('certification', models.CharField(blank=True, default='', max_length=200)),
                ('runtime', models.IntegerField(blank=True, default=0)),
                ('kind', models.CharField(blank=True, default='', max_length=200)),
                ('genres', models.CharField(blank=True, default='', max_length=200)),
                ('director', models.CharField(blank=True, default='', max_length=500)),
                ('actors', models.TextField(blank=True, default='')),
                ('overview', models.TextField(blank=True, default='')),
                ('original_language', models.CharField(blank=True, default='', max_length=200)),
                ('original_country', models.CharField(blank=True, default='', max_length=200)),
                ('tv_type', models.CharField(blank=True, default='', max_length=200)),
                ('poster_path', models.CharField(blank=True, default='', max_length=200)),
                ('backdrop_path', models.CharField(blank=True, default='', max_length=200)),
                ('trailer', models.CharField(blank=True, default='', max_length=200)),
                ('homepage', models.URLField(blank=True, default='')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-year', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', help_text='Comments only for ders')),
                ('notes', models.TextField(blank=True, default='', help_text='Comments for everyone')),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('sv', models.SmallIntegerField(choices=[(-1, 'Pending'), (0, 'Rejected'), (1, 'Edited'), (2, 'Approved')], default=-1)),
                ('sf', models.SmallIntegerField(choices=[(-1, 'Pending'), (0, 'Rejected'), (1, 'Edited'), (2, 'Approved')], default=-1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('special', models.TextField(blank=True, default='', help_text='To select the movie in one special list, like Bollywood')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.movie')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
